### ISSUE TITLE
proposal for separate namespace for each algorithm/utility category

### ISSUE THREAD

**Issue by apyasic** [IBMStreams/streamsx.sparkMLLib#3]
@ankitpas  as Spark mllib provides wide range of  learning algorithms and utilities, including classification, regression, clustering, collaborative filtering, dimensionality reduction
 we probably should consider to have a separate namespace for each algorithms and utility category to improve the toolkit user and developer experience.

**Comment by ankitpas** [comment]
This makes sense so I have updated the operators to reside in separate namespaces mirroring their package location in Spark.
