### ISSUE TITLE
Proposal for extension - Additional output attributes from models 

### ISSUE THREAD

**Issue by manojsingh101** [IBMStreams/streamsx.sparkMLLib#31]
Spark models have additional prediction information which may be required in certain cases. e.g. Naive Bayes has list of of probabilities, KMeans has cluster centers and cost, etc. It would be good to have these as optional output attributes in operators.
I forked the sparkMLLib toolkit and modified it for according to my project requirement.
https://github.com/manojsingh101/streamsx.sparkMLLib

The modifications are for SparkNaiveBayes operator to output list of probabilities for each prediction class.
Changes:
1. Add a new boolean attribute as parameter "getProbabilities"
2. Add a new output attribute of type list<float64> which would required only if getProbabilities=true
3. Add a new function to generate a feature vector of float64 from a line of text to pass to model.
    com.ibm.streamsx.sparkmllib.utils.Util.getFeatureVector
4. A sample application to use the new operator.

Can we extend other models to output similar relevant attributes to make these operators more feature rich?

**Comment by joergboe** [comment]
I opened a PR to review the changes.

**Comment by joergboe** [comment]
Can you pleas add a model directory for the sample and input data files for the sample.

**Comment by joergboe** [comment]
Functionality is included in version 1.3
