### ISSUE TITLE
Hardcoded lib directory

### ISSUE THREAD

**Issue by raghukiran1224** [IBMStreams/streamsx.sparkMLLib#32]
With Spark 2.x, the lib directory is no longer part of the distribution. It is now called jars. It would probably be better if the SPARK_LIB environment variable is used for pointing to the right lib directory. This will ensure that there are no class not found exceptions thrown.

**Comment by joergboe** [comment]
Or do you mean SPARK_HOME ?

**Comment by raghukiran1224** [comment]
no, SPARK_HOME is fine.. the challenge is with https://github.com/IBMStreams/streamsx.sparkMLLib/blob/master/com.ibm.streamsx.sparkmllib/impl/java/src/com/ibm/streamsx/sparkmllib/AbstractSparkMLlibOperator.java#L48

where @Libraries({"@SPARK_HOME@/lib/*"}) has "lib" hardcoded.

Spark 2.x build puts the jars in "@SPARK_HOME@/jars/" directory.

**Comment by joergboe** [comment]
from now spark2.x should be used. v1.2.0 changes the path to @SPARK_HOME@/jars/
