### ISSUE TITLE
Add documentation on what sparkMaster parameter is

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.sparkMLLib#8]
More details on how the sparkmaster is used, e.g. when should I use something apart from the default.

In messing around with spark, I've found you can't have multiple spark contexts in a single JVM, so does this have an impact on how my operators from this toolkit can be fused?

Somewhat related to the discussion in issue #2 

SPLDOC allows pages and overviews for a namespace, so the documentation could be in a single location and referenced by each operator.

**Comment by joergboe** [comment]
Resolved with commit 90932646615d7899b1678d0798cdf8fc960ea114
